project: 
  type: book

book: 
  page-navigation: true
  title: "CPS Acoustic Classification" 
  site-url: "https://nmfs-swfsc-ast.github.io/echo-class/" 
  repo-url: "https://github.com/nmfs-swfsc-ast/echo-class"
  repo-actions: [edit, source, issue]
  favicon: assets/favicon.ico
  downloads: [pdf, docx]
  search: true
  author:
    - name: Alice Beittel
      affiliations:
        - name: NOAA Southwest Fisheres Science Center
          department: Southwest Fisheries Science Center
   # - name: Eva Nováková
   #   institute: test
   #   affiliations:
   #     - name: NOAA Fisheries
   #       department: West Coast Regional Office
   #       institute: test
   # - name: Matti Meikäläinen
   #   affiliations:
   #     - name: NOAA Fisheries
   #       department: Southwest Fisheries Science Center
  chapters:
    - index.qmd
    - content/background.qmd
    - content/acquisition.qmd
    - content/workflow.qmd
    - content/add-content.qmd
    - content/customizing.qmd
    - content/rendering.qmd
    - content/figures_and_tables.qmd
    - content/code.qmd
    - content/adding-refs.qmd
    - content/references.qmd

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://media.fisheries.noaa.gov/dam-migration-miss/md_YPyChZ2sgSi5.png?1595971802"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: "https://www.fisheries.noaa.gov/west-coast/science-data/advanced-survey-technologies-assessments-california-current-ecosystem"
        text: "SWFSC AST"
    style: "docked"
    search: true
    collapse-level: 1

bibliography: [content/references.bib]

execute:
  echo: false
  code-overflow: wrap

format:
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"
    keep-tex: true
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: [cosmo, assets/theme.scss] 
    toc: true
    toc-depth: 3
    number-sections: false

filters:
  - assets/include-files.lua
  - quarto

# Comment next 2 lines if the PDF is having trouble
metadata-files:
  - _frontmatter.yml
 
