```{r, echo=FALSE}
render.date <- format(Sys.time(), format = "%F %T", usetz = TRUE)
```

**Last updated:** `{r} render.date`

# Welcome {.unnumbered}

\[\[\[enter cool image of CPS survey\]\]\]

[West Coast coastal pelagic species](https://www.fisheries.noaa.gov/species/west-coast-coastal-pelagic-species) play an important role in the California Current ecosystem. They’re food sources for marine mammals, sea birds, and larger fish, and they support commercial and recreational fisheries. The biomass and abundance estimates derived from this project are used in stock assessment models to support sustainable fisheries.

## Document Objective:

This resource will serve as a tutorial to demonstrate how the SWFSC uses acoustic data generate biomass estimates of Coastal Pelagic Species from Baja, Mexico to Vancouver, Canada.

| As part of our commitment to open science, reproducibility, and transparency, we provide this metadata guide to compliment our public-domain data.
| 
| Please consider this resource to be a **Living Document**. The code in this repository is regularly being updated and improved. 
| 
| Do not hesitate to reach out (to us at either alice.beittel\@noaa.gov or [GitHub issues](https://github.com/nmfs-swfsc-ast/echo-class/issues), especially if you find discrepancies in the data or want to suggest improvements to infrastructure. Thank you in advance for your collaboration and partnership with us as we develop our future data universe.

## User Resources

## Cite This Data

\[enter text on how to do this\]

## NOAA README

This repository is a scientific product and is not official communication of the National Oceanic and Atmospheric Administration, or the United States Department of Commerce. All NOAA GitHub project code is provided on an ‘as is’ basis and the user assumes responsibility for its use. Any claims against the Department of Commerce or Department of Commerce bureaus stemming from the use of this GitHub project will be governed by all applicable Federal law. Any reference to specific commercial products, processes, or services by service mark, trademark, manufacturer, or otherwise, does not constitute or imply their endorsement, recommendation or favoring by the Department of Commerce. The Department of Commerce seal and logo, or the seal and logo of a DOC bureau, shall not be used in any manner to imply endorsement of any commercial product or activity by DOC or the United States Government.

## NOAA License

Software code created by U.S. Government employees is not subject to copyright in the United States (17 U.S.C. §105). The United States/Department of Commerce reserve all rights to seek and obtain copyright protection in countries other than the United States for Software authored in its entirety by the Department of Commerce. To this end, the Department of Commerce hereby grants to Recipient a royalty-free, nonexclusive license to use, copy, and create derivative works of the Software outside of the United States.

```{=openxml}
<w:p><w:r><w:br w:type="page"/></w:r></w:p>
```
