---
title: "Daily Shipboard Acoustic Operations"
editor: visual
---

While conducting acoustic-trawl surveys, the acoustics team is responsible for ensuring the proper operation of all acoustic instruments, processing acoustic transects, and determining CPS school sites for nightly trawling. This page details the daily tasks the acoustics team will undertake while at sea.

### Quick Links:

-   [Daily Ship Acoustic Operations document](https://docs.google.com/document/d/1PiaZtjqStg0TtknSAm8bVK0JXxvjO31eomtCiPnFvgA/edit?tab=t.0) - Daily task list for sunrise, throughout the day, and sunset. Updated each leg.

-   [Leg Summaries and Passdown Notes](https://docs.google.com/document/d/1brlI4uXMfdw5mfewRfdAoZAE4WgbCdjrjqkhapuuV6U/edit?usp=drive_link) - Active document with all leg summaries and passdown notes. Updated each leg.

### **Orientation to the Echoview PC:**

The main survey directory is **C:\\SURVEY\\\[Survey Name Code\].** *For example for 2025 the directory is: `C:\SURVEY\2506SH`.* All work by the acoustician must be done inside of this folder. DO NOT work with data stored in the `Survey_Backup` folder on the NAS Drive – this folder is mirrored from the C:\\ drive and will be overwritten during subsequent backups.

\
The **C:\\SURVEY\\\[Survey Name Code\]** directory contains all survey-related items excluding sounder data. Sounder data is instead recorded to local (or external) hard drives on each individual system and/or backed up to the NAS drive.

### Troubleshooting:

-   For issues on echosounder software, refer to the Set Up for Acoustic Trawl page and instillation settings for the echosounder.

-   For issues on ship networking, contact the ship ET and ship survey technician

-   The AST group chat is always available for additional technical and emotional support :)
